[package]
name = "marain-hook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subprocess = "0.2.9"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
